POST http://localhost:8080/events/6/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphY2suc3BhcnJvd0BnbWFpbC5jb20iLCJleHAiOjE3NTc0MjU4ODcsInVzZXJJZCI6Mn0.YWcDAiDdBrldToa5rHRgAE_azcQxAvOI19ccFb8DH6k
